global _GAME_WINDOW_ID := "ahk_exe Grim Dawn.exe"
global _CONFIG_FILE_EXTENSION := "ini"
global _AUTOMATIC_HOTKEY_SUSPENSION_LOOP_DELAY := 1000

global _HOTKEY_MODIFIERS := "~*$"
global _HOTKEY_MODIFIERS_NATIVE_FUNCTION_BLOCKED := "*$"
global _MAX_NUMBER_OF_COMBINATIONS := 9

global _AUTOCAST_BY_TOGGLE_DELAY := 100
global _AUTOCAST_BY_TOGGLE_SECTION_NAME := "autocast by toggle"

global _COMBOS_IN_BETWEEN_DELAY := 200
global _COMBOS_INITIAL_DELAY := false
global _COMBOS_STOP_ON_RELEASE := false
global _COMBOS_DOUBLE_PRESS := false
global _COMBOS_DOUBLE_PRESS_TIME_GAP := 250
global _COMBOS_KEY_NATIVE_FUNCTION := true

global _CENTER_CASTS_CLOSER_NOT_CENTER := false
global _CENTER_CASTS_INITIAL_DELAY := 0
global _CENTER_CASTS_DELAY := 200
global _CENTER_CASTS_DISTANCE := 25
global _CENTER_CASTS_HEIGHT_CORRECTION := 60
global _CENTER_CASTS_PAUSE_AFTER_MOVING_CURSOR := 10

global _COMBO_HOLDS_DELAY_FROM_PRESS_TO_HOLD := 150
global _COMBO_HOLDS_HOLD_ON_DOUBLE_PRESS := false
global _COMBO_HOLDS_DOUBLE_PRESS_TIME_GAP := 250

global _PERIODIC_CASTS_IN_BETWEEN_DELAY := 100
global _PERIODIC_CASTS_INITIAL_DELAY := 0
global _PERIODIC_CASTS_DOUBLE_PRESS := false
global _PERIODIC_CASTS_DOUBLE_PRESS_TIME_GAP := 250

global _CAMERA_ANGLE := 60
global _CAMERA_DELAY := 40

global _HIDE_ITEMS_DURATION := 3000

global _CLICKER_DELAY := 50
