global _GAME_WINDOW_ID := "ahk_exe Grim Dawn.exe"
global _CONFIG_FILE_EXTENSION := "ini"
global _AUTOMATIC_HOTKEY_SUSPENSION_LOOP_DELAY := 1000

global _HOTKEY_MODIFIERS := "~*$"
global _MAX_NUMBER_OF_COMBINATIONS := 9

global _AUTOCASTING_PRESSED_BUTTONS := "0,1,2,3,4,5,6,7,8,9"
global _AUTOCASTING_DELAY := 100
global _AUTOCASTING_TEMPORARY_BLOCK_DURATION := 100

global _COMBOS_IN_BETWEEN_DELAY := 200
global _COMBOS_INITIAL_DELAY := false
global _COMBOS_STOP_ON_RELEASE := false

global _CENTER_CASTS_CLOSER_NOT_CENTER := false
global _CENTER_CASTS_INITIAL_DELAY := 0
global _CENTER_CASTS_DELAY := 200
global _CENTER_CASTS_DISTANCE := 75
global _CENTER_CASTS_HEIGHT_CORRECTION := 60
global _CENTER_CASTS_PAUSE_AFTER_MOVING_CURSOR := 10

global _COMBO_HOLDS_DELAY_FROM_PRESS_TO_HOLD := 150
global _COMBO_HOLDS_HOLD_ON_DOUBLE_PRESS := false
global _COMBO_HOLDS_DOUBLE_PRESS_TIME_GAP := 250

global _PERIODIC_CASTS_IN_BETWEEN_DELAY := 1000
global _PERIODIC_CASTS_INITIAL_DELAY := 0

global _CAMERA_ANGLE := 60
global _CAMERA_DELAY := 40

global _HOLD_TO_HIDE_ITEMS_TIME_BUFFER := 1000
