global _GAME_WINDOW_ID := "ahk_exe Grim Dawn.exe"
global _CONFIG_FILE_EXTENSION := "ini"
global _AUTOMATIC_HOTKEY_SUSPENSION_LOOP_DELAY := 1000
global _KILL_ON_EXIT := false
global _TITLE_MATCH_MODE := 3

global _HOTKEY_MODIFIERS := "~*$"
global _HOTKEY_MODIFIERS_NATIVE_FUNCTION_BLOCKED := "*$"
global _MAX_NUMBER_OF_COMBINATIONS := 9

global _AUTOCAST_BY_HOLD_IN_BETWEEN_DELAY := 100
global _AUTOCAST_BY_HOLD_INITIAL_DELAY := 0
global _AUTOCAST_BY_HOLD_INNER_DELAY := 0
global _AUTOCAST_BY_HOLD_DOUBLE_PRESS := false
global _AUTOCAST_BY_HOLD_DOUBLE_PRESS_TIME_GAP := 250
global _AUTOCAST_BY_HOLD_SECTION_NAME := "autocast by hold"
global _AUTOCAST_BY_HOLD_KEY_NATIVE_FUNCTION := true

global _AUTOCAST_BY_TOGGLE_DELAY := 100
global _AUTOCAST_BY_TOGGLE_SECTION_NAME := "autocast by toggle"
global _AUTOCAST_BY_TOGGLE_RIGHT_AWAY := false

global _AUTOMATIC_CAMERA_SECTION_NAME := "automatic camera"
global _AUTOMATIC_CAMERA_INITIAL_DELAY := 200
global _AUTOMATIC_CAMERA_DELAY := 100
global _AUTOMATIC_CAMERA_IGNORE_AREA_SHAPE := "circle"
global _AUTOMATIC_CAMERA_SHAPE_CIRCLE := "circle"
global _AUTOMATIC_CAMERA_SHAPE_RECTANGLE := "rectangle"
global _AUTOMATIC_CAMERA_IGNORE_AREA_SIZE := 50
global _AUTOMATIC_CAMERA_IGNORE_SEGMENT_ANGLE := 20

global _COMBOS_IN_BETWEEN_DELAY := 200
global _COMBOS_INITIAL_DELAY := 0
global _COMBOS_STOP_ON_RELEASE := false
global _COMBOS_DOUBLE_PRESS := false
global _COMBOS_DOUBLE_PRESS_TIME_GAP := 250
global _COMBOS_KEY_NATIVE_FUNCTION := true
global _COMBOS_SECTION_NAME := "combo presses"

global _CENTER_CASTS_INITIAL_DELAY := 0
global _CENTER_CASTS_DELAY := 200
global _CENTER_CASTS_DISTANCE := 25
global _CENTER_CASTS_HEIGHT_CORRECTION := 60
global _CENTER_CASTS_OFF_CENTER := false
global _CENTER_CASTS_PAUSE_AFTER_MOVING_CURSOR := 10
global _CENTER_CASTS_SECTION_NAME := "center casts"

global _COMBO_HOLDS_DELAY_FROM_PRESS_TO_HOLD := 0
global _COMBO_HOLDS_HOLD_ON_DOUBLE_PRESS := false
global _COMBO_HOLDS_DOUBLE_PRESS_TIME_GAP := 250
global _COMBO_HOLDS_KEY_NATIVE_FUNCTION := true
global _COMBO_HOLDS_SECTION_NAME := "combo holds"

global _CAMERA_ANGLE := 60
global _CAMERA_DELAY := 40
global _CAMERA_SECTION_NAME := "camera"

global _HIDE_ITEMS_DURATION := 3000
global _HIDE_ITEMS_SECTION_NAME := "hide items"

global _FIXED_CLICKS_DELAY := 25
global _FIXED_CLICKS_INITIAL_DELAY := 0
global _FIXED_CLICKS_SECTION_NAME := "fixed clicks"
global _FIXED_CLICKS_KEY_NATIVE_FUNCTION := true
global _FIXED_CLICKS_REPEAT := 0
global _FIXED_CLICKS_TRANSLATION := 0,0
global _FIXED_CLICKS_GO_BACK := true

global _RELATIVE_CLICKS_SECTION_NAME := "relative clicks"
global _RELATIVE_CLICKS_DELAY := 25

global _HACKER_SECTION_NAME := "hacker"
global _HACKER_PROGRAM_NAME := "GDHacker.exe"
global _HACKER_SPEED_CODE := 0
global _HACKER_DEFAULT_SPEEDS := "2,1"
global _HACKER_FREEZE_TRIBUTES := false
global _HACKER_FREEZE_CODE := 1
global _HACKER_STATS_CODE := 2
